apiVersion: v1
kind: Service
metadata:
  name: mock-telldus-np-service
  labels:
    app: mock-telldus 
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    targetPort: 8080
    protocol: TCP
  selector:
    app: mock-telldus 


